### ISSUE TITLE
AC3 or DD audio sync issue.

### ISSUE THREAD

**Issue by docthomas** [Pivosgroup/buildroot-linux#7] opened 2012-11-11 11:40 UTC
When playing files that have AC3 or DD encoding the audio is out of sync.  If I turn off AC3/DD capable option in System Settings the files play fine with multi channel PCM.  DTS files work fine also.  It just seems to be AC3/DD

**Comment by davilla** [comment] 2012-11-11 16:49
Impossible to reproduce without a sample.

**Comment by yang299kms** [comment] 2012-11-14 01:49
http://dl.dropbox.com/u/76471871/Output-001.mkv
that video has DD audio, i have my xios connected to a denon 3313CI, if i enable receiver supports DD the audio is out of sync with video, but if i disable receiver supports DD and output stereo the audio is better but not perfectly in sync

**Comment by dools** [comment] 2012-11-19 21:25
Im seeing the same issue using the beta from 100912. My pioneer receiver (can get the model number tonight if it helps) supports DD and DTS. Disabling DD improves the sync.

love your work davilla.

**Comment by speedst3r** [comment] 2012-11-21 14:49
I get sync issues with this file but not other DD files I have.

Mediainfo says the audio bitrate is 384Kbps but CodecInfo on the XIOS during playback reports 375Kbps.

**Comment by yang299kms** [comment] 2012-11-22 00:29
Can you cut me a sample of your file that works?
update: i think the 384 vs 375 is basically doing math using 1024 vs 1000

**Comment by speedst3r** [comment] 2012-11-22 21:35
Well I never used to have issues, but looks like I'm seeing it now with pass through enabled to a Pioneer VSX-1019, at both 720p and 1080p resolutions.

This was with buildroot-linux bf5b0610f6fe9ff43a43458bd67f02e4f61e1ae8

**Comment by ghost** [comment] 2012-12-01 20:02
This happens to me to, definitely on DD audio. I have Denon avr-1712

-confirmed that it happens on my AC-3 videos too.

This is with mkv files served over nfs, SD dvd rips.

**Comment by davilla** [comment] 2012-12-01 21:22
@ssk60, same buildroot-linux version as @speedst3r ?

**Comment by ghost** [comment] 2012-12-01 22:01
sorry, mine is all for the binary release 100912. Am I not supposed to report those here?

**Comment by davilla** [comment] 2012-12-01 23:03
I need to know versions so when someone says 'me too' then I can tell if they are running some older version or the current buildroot-linux build which is where I'm working.

**Comment by speedst3r** [comment] 2012-12-02 22:11
AV sync for AC3 tracks is much better (or even resolved) in 2e8a464

**Comment by yang299kms** [comment] 2012-12-03 02:04
Ya much better, almost can't tell its out of sync or in sync

**Comment by davilla** [comment] 2013-01-05 18:12
closing as fixed

**Closed as completed** 2013-01-05 18:13 UTC
